name: user
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  intl: ^0.17.0
  json_annotation: ^4.0.1
  flutter_phoenix: ^0.1.0
  country_code_picker: ^1.3.15
  grouped_buttons: ^1.0.4
  google_fonts: ^2.0.0
  image_auto_slider: ^0.0.3
  image_slider: ^1.0.2
  pin_code_text_field: ^1.7.1
  page_transition: ^1.1.6
  shared_preferences: ^2.0.5
  toast: ^0.1.5
  circular_bottom_navigation: ^1.0.1
  carousel_slider: ^2.3.1
  url_launcher: ^6.0.3
  shimmer_animation: ^0.1.1
  path_provider: ^2.0.1
  #  horizontal_calendar_widget: ^1.0.2
  razorpay_flutter: ^1.2.6
  flutter_paystack: ^1.0.5
  flutter_share: ^1.0.2+1
  geolocator: ^7.0.1
  geocoder: ^0.2.1
  google_maps_flutter: ^2.0.2
  flutter_google_places: ^0.3.0
  flutter_local_notifications: ^5.0.0+1
  firebase_messaging: ^10.0.1
  sqflite: ^1.3.1+1
  progress_dialog: ^1.2.4
  image_picker: ^0.7.4
  flutter_datetime_picker: ^1.5.0
  flutter_html: ^1.3.0
  fbutton: ^2.0.1
  flutter_bloc: ^6.0.1
  firebase_auth: ^1.3.0
  firebase_core : ^1.2.1
  http: ^0.13.1
  flutter_credit_card: ^2.0.0
  pdf: ^3.1.0
  flutter_full_pdf_viewer: ^1.0.6
  printing: ^5.0.4
  mapbox_search: ^2.1.0+1
  http_auth: ^1.0.0

#dependency_overrides:
#  intl: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  #  json_serializable: ^3.4.1
  #  intl_translation: ^0.17.10+1
  flutter_launcher_icons: ^0.9.0
  change_app_package_name: ^1.0.0
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "images/logos/logo_user.png"

flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - images/
    - images/account/
    - images/address/
    - images/custom/
    - images/footermenu/
    - images/icons/
    - images/logos/
    - images/maincategory/
    - images/veg/
    - images/veg/Sellers/
    - images/veg/Vegetables/
    - images/payment/
    - images/demosliderimage/
    - images/refernearn/
    - assets/
    - assets/category/
    - assets/products/
    - assets/restaurant/
    - assets/slider/
    - assets/user_profile/
    - assets/payment/
    - assets/onboarding/
    - assets/fonts/OpenSans-Regular.ttf
    - assets/fonts/OpenSans-Bold.ttf
    - assets/fonts/OpenSans-Italic.ttf
    - assets/fonts/OpenSans-BoldItalic.ttf